apiVersion: v1
kind: Pod
metadata:
  name: myvolhostpath
spec:
  containers:
    - name: centos
      image: centos
      command: ["/bin/bash", "-c", "sleep 15000"]
      vloumeMounts:
        - mountPath: "/tmp/hostpath"
          name: testvolume
  volumes:
    - name: testvolume
      hostPath:
        path: /tmp/data
