apiVersion: v1
kind: Services
metadata:
  - name: nodeportsvc
    label:
      env: demo
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 80
  selector:
    # matchLabels:
    env: demo
