# name Space Creation
---
apiVersion: v1
kind: Namespace
metadata:
  name: clinicall-ns
---
# Pod Creation
apiVersion: v1
kind: Pod
metadata:
  name: clinicallFrontend
  namespace: clinicall-ns
  labels:
    app: clinicall-frontend-app
spec:
  containers:
    - name: clinicall-frontend-image
      image: nginx
      resources:
        requests:
          cpu: ...
          memory: ...
        limits:
          cpu: ...
          memory: ...
      ports:
        - containerPort: 80
---
# Services Creation
apiVersion: v1
kind: Service
metadata:
  name: shopping-site-cluster-svc
spec:
  type: NodePort
  selector:
    app: clinicall-frontend-app
  ports:
    - port: 80
      targetport: 80
      nodePort: 30002
