---
apiVersion: v1
kind: Namespace
metadata:
  name: shoppingnamespace
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: shopping-site-replica-ctrl
  namespace: shoppingnamespace
spec:
  replicas: 2
  selector:
    app: clinicall_frontend_app
  template:
    metadata:
      name: clinicall_frontend_replicas
      labels:
        app: clinicall_frontend_app
    spec:
      containers:
        - name: clinicall_frontend_pod
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: clinicall_replicas_Services
spec:
  type: NodePort
  selector:
    app: clinicall_frontend_app
  ports:
    - port: 81
      targetPort: 80
      nodePort: 30002
