group: apps/v1
apiVersion: v1
kind: ReplicaSet
metadata:
  - name: nginx-rs
    labels:
      env: development
spec:
  template:
    metadata:
      labels:
        env: development
    spec:
      containers:
        - name: nginx_pod
          image: nginx:latest
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLables:
      env: development

