upstream backends {
    server container1:80;
    server container2:80;
}

server {
    listen   80;
    listen [::]:80;
    server_name localhost;

    location / {
        proxy_pass http://backends;
    }
}
