events{

}
http{
    include mime.types;
    server{
        listen 80;
        server_name 13.203.230.200 ec2-13-203-230-200.ap-south-1.compute.amazonaws.com;
        root /new/; 
        index index.php index.html;
        location / {
            try_files $uri $uri/ =404
        }
        location ~\.php${
             include fastcgi.conf
             fastcgi_pass unix:
        }
    }
}