events{

}
http{
    include mime.types;
    server{
        listen 80;
        server_name 13.235.77.128;
        root /new/; 
        location /contact {
            return 200 "Hello you are inside the custom location !!"

        }
    }
}