events{

}
http{
    # types{
    #     text/html html;
    #     text/css css ;

    # }
    types_hash_max_size 4096;
    types_hash_bucket_size 128;

    include mime.types ;

    server{
        listen 80;
        server_name ec2-13-235-77-128.ap-south-1.compute.amazonaws.com;
        root /new/;
    }
}

# nginx -t
# nginx -s reload |  systemctl reload nginx
# open the log 
# cat /var/log/nginx/*
# we can find the css of that project so we had to config in 
# -> $ cd /etc/nginx/mime.types 