events{

}
http {
    include mime.types;
    types_hash_max_size 4096;
    types_hash_bucket_size 128;
    server{

        listen 80;
        server_name 15.206.212.67 ec2-15-206-212-67.ap-south-1.compute.amazonaws.com;

        location / {
            proxy_pass http://localhost:3000;

        }
    }
    server{

        listen 8080;
        server_name 15.206.212.67 ec2-15-206-212-67.ap-south-1.compute.amazonaws.com;

        location / {
            rewrite ^/?$ /en/ break;
            proxy_pass http://localhost:3000/en;
        }
    }
}
