apiVersion: v1
kind: ServiceAccount
metadata:
  name: others
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: other-role
rules:
  - apiGroup: ["*"]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: other-role-binding
subjects:
  - kind: ServiceAccount
    name: others
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: other-role
  apiGroup: rbac.authorization.k8s.io
