kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-only
  namespace: default
rules:
  - apiGroup: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroup: [""]
    resources: ["deployement", "statefulsets"]
    verbs: ["get", "watch", "list", "create", "update", "delete"]
  - apiGroup: [""]
    resources: ["daemonsets"]
    verbs: ["get", "watch", "list", "create", "update"]
  - apiGroup: ["*"]
    resources: ["*"]
    verbs: ["*"]
